name: deploy
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_LAMBDA_SECRET_KEY }}
  AWS_DB_HOST: ${{ secrets.AWS_DB_HOST }}
  AWS_DB_USER: ${{ secrets.AWS_DB_USER }}
  AWS_DB_PASSWORD: ${{ secrets.AWS_DB_PASSWORD }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # build the .NET backend
  deploy-backend:
  
    runs-on: ubuntu-latest

    steps:
      # setup
      - name: Check-out repo
        uses: actions/checkout@v3
        
      # build app and update db
      - name: Build backend
        working-directory: ./backend
        run: |
          dotnet publish --output "./bin/publish" --configuration "Release" --framework "net6.0" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false
        
      - name: Update database
        working-directory: ./backend
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef database update
        
      # deploy to lambda
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1.0.3

      - name: Zip backend
        working-directory: ./backend/bin/publish
        run: zip backend.zip *
          
      - name: Upload zip to Lambda
        working-directory: ./backend/bin/publish
        run: aws lambda update-function-code --function-name FintrakBackend --zip-file fileb://backend.zip --region us-east-1 --environment "Variables={fintrak_dbserver=$AWS_DB_HOST,fintrak_dbuser=$AWS_DB_USER,fintrak_dbpassword=$AWS_DB_PASSWORD}"
          
  #deploy-frontend:
    #runs-on: ubuntu-latest
    
          

